

ssh:
	ssh -i "cs-po1.pem" ec2-user@ec2-34-239-42-159.compute-1.amazonaws.com

sftp:
	sftp -i "cs-po1.pem" ec2-user@ec2-34-239-42-159.compute-1.amazonaws.com

locs:
	cortex profiles  save-schema location-demographics.schema.json

segs:
	cortex profiles  save-schema viewer-segment.schema.json

view:
	cortex profiles  save-schema view.schema.json
